package m.pojos;
// Generated 05-22-2016 04:37:30 AM by Hibernate Tools 4.3.1



/**
 * Dificultades generated by hbm2java
 */
public class Dificultades  implements java.io.Serializable {


     private int iddificultad;
     private Persona persona;
     private String enproduccion;
     private String enventa;

    public Dificultades() {
    }

	
    public Dificultades(int iddificultad, Persona persona) {
        this.iddificultad = iddificultad;
        this.persona = persona;
    }
    public Dificultades(int iddificultad, Persona persona, String enproduccion, String enventa) {
       this.iddificultad = iddificultad;
       this.persona = persona;
       this.enproduccion = enproduccion;
       this.enventa = enventa;
    }
   
    public int getIddificultad() {
        return this.iddificultad;
    }
    
    public void setIddificultad(int iddificultad) {
        this.iddificultad = iddificultad;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getEnproduccion() {
        return this.enproduccion;
    }
    
    public void setEnproduccion(String enproduccion) {
        this.enproduccion = enproduccion;
    }
    public String getEnventa() {
        return this.enventa;
    }
    
    public void setEnventa(String enventa) {
        this.enventa = enventa;
    }




}


