package m.pojos;
// Generated 05-22-2016 04:37:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idpersona;
     private Zona zona;
     private String nombre;
     private int edad;
     private Boolean sexo;
     private Double ingresosanuales;
     private Integer lugardeventa;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Dificultades> dificultadeses = new HashSet<Dificultades>(0);
     private Set<Produccion> produccions = new HashSet<Produccion>(0);

    public Persona() {
    }

	
    public Persona(int idpersona, Zona zona, String nombre, int edad) {
        this.idpersona = idpersona;
        this.zona = zona;
        this.nombre = nombre;
        this.edad = edad;
    }
    public Persona(int idpersona, Zona zona, String nombre, int edad, Boolean sexo, Double ingresosanuales, Integer lugardeventa, Set<Usuario> usuarios, Set<Dificultades> dificultadeses, Set<Produccion> produccions) {
       this.idpersona = idpersona;
       this.zona = zona;
       this.nombre = nombre;
       this.edad = edad;
       this.sexo = sexo;
       this.ingresosanuales = ingresosanuales;
       this.lugardeventa = lugardeventa;
       this.usuarios = usuarios;
       this.dificultadeses = dificultadeses;
       this.produccions = produccions;
    }
   
    public int getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(int idpersona) {
        this.idpersona = idpersona;
    }
    public Zona getZona() {
        return this.zona;
    }
    
    public void setZona(Zona zona) {
        this.zona = zona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public Boolean getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Boolean sexo) {
        this.sexo = sexo;
    }
    public Double getIngresosanuales() {
        return this.ingresosanuales;
    }
    
    public void setIngresosanuales(Double ingresosanuales) {
        this.ingresosanuales = ingresosanuales;
    }
    public Integer getLugardeventa() {
        return this.lugardeventa;
    }
    
    public void setLugardeventa(Integer lugardeventa) {
        this.lugardeventa = lugardeventa;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Dificultades> getDificultadeses() {
        return this.dificultadeses;
    }
    
    public void setDificultadeses(Set<Dificultades> dificultadeses) {
        this.dificultadeses = dificultadeses;
    }
    public Set<Produccion> getProduccions() {
        return this.produccions;
    }
    
    public void setProduccions(Set<Produccion> produccions) {
        this.produccions = produccions;
    }




}


