package m.pojos;
// Generated 05-22-2016 04:37:30 AM by Hibernate Tools 4.3.1



/**
 * Produccion generated by hbm2java
 */
public class Produccion  implements java.io.Serializable {


     private int idproduccion;
     private Persona persona;
     private Producto producto;
     private double preciodeventapormayor;
     private Double preciodeventapormenor;
     private String unidaddemedida;
     private int tamanodeproduccion;

    public Produccion() {
    }

	
    public Produccion(int idproduccion, Persona persona, Producto producto, double preciodeventapormayor, String unidaddemedida, int tamanodeproduccion) {
        this.idproduccion = idproduccion;
        this.persona = persona;
        this.producto = producto;
        this.preciodeventapormayor = preciodeventapormayor;
        this.unidaddemedida = unidaddemedida;
        this.tamanodeproduccion = tamanodeproduccion;
    }
    public Produccion(int idproduccion, Persona persona, Producto producto, double preciodeventapormayor, Double preciodeventapormenor, String unidaddemedida, int tamanodeproduccion) {
       this.idproduccion = idproduccion;
       this.persona = persona;
       this.producto = producto;
       this.preciodeventapormayor = preciodeventapormayor;
       this.preciodeventapormenor = preciodeventapormenor;
       this.unidaddemedida = unidaddemedida;
       this.tamanodeproduccion = tamanodeproduccion;
    }
   
    public int getIdproduccion() {
        return this.idproduccion;
    }
    
    public void setIdproduccion(int idproduccion) {
        this.idproduccion = idproduccion;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public double getPreciodeventapormayor() {
        return this.preciodeventapormayor;
    }
    
    public void setPreciodeventapormayor(double preciodeventapormayor) {
        this.preciodeventapormayor = preciodeventapormayor;
    }
    public Double getPreciodeventapormenor() {
        return this.preciodeventapormenor;
    }
    
    public void setPreciodeventapormenor(Double preciodeventapormenor) {
        this.preciodeventapormenor = preciodeventapormenor;
    }
    public String getUnidaddemedida() {
        return this.unidaddemedida;
    }
    
    public void setUnidaddemedida(String unidaddemedida) {
        this.unidaddemedida = unidaddemedida;
    }
    public int getTamanodeproduccion() {
        return this.tamanodeproduccion;
    }
    
    public void setTamanodeproduccion(int tamanodeproduccion) {
        this.tamanodeproduccion = tamanodeproduccion;
    }




}


