package m.pojos;
// Generated 05-22-2016 04:37:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idproducto;
     private String nombreproducto;
     private String detalledeproducto;
     private Set<Produccion> produccions = new HashSet<Produccion>(0);
     private Set<Categoria> categorias = new HashSet<Categoria>(0);

    public Producto() {
    }

	
    public Producto(int idproducto, String nombreproducto) {
        this.idproducto = idproducto;
        this.nombreproducto = nombreproducto;
    }
    public Producto(int idproducto, String nombreproducto, String detalledeproducto, Set<Produccion> produccions, Set<Categoria> categorias) {
       this.idproducto = idproducto;
       this.nombreproducto = nombreproducto;
       this.detalledeproducto = detalledeproducto;
       this.produccions = produccions;
       this.categorias = categorias;
    }
   
    public int getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(int idproducto) {
        this.idproducto = idproducto;
    }
    public String getNombreproducto() {
        return this.nombreproducto;
    }
    
    public void setNombreproducto(String nombreproducto) {
        this.nombreproducto = nombreproducto;
    }
    public String getDetalledeproducto() {
        return this.detalledeproducto;
    }
    
    public void setDetalledeproducto(String detalledeproducto) {
        this.detalledeproducto = detalledeproducto;
    }
    public Set<Produccion> getProduccions() {
        return this.produccions;
    }
    
    public void setProduccions(Set<Produccion> produccions) {
        this.produccions = produccions;
    }
    public Set<Categoria> getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Set<Categoria> categorias) {
        this.categorias = categorias;
    }




}


