package m.pojos;
// Generated 05-19-2016 02:23:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Produccion generated by hbm2java
 */
@Entity
@Table(name="produccion"
    ,schema="public"
)
public class Produccion  implements java.io.Serializable {


     private int idproduccion;
     private Producto producto;
     private double preciodeventapormayor;
     private Double preciodeventapormenor;
     private String unidaddemedida;
     private int tamanodeproduccion;
     private Set personas = new HashSet(0);

    public Produccion() {
    }

	
    public Produccion(int idproduccion, double preciodeventapormayor, String unidaddemedida, int tamanodeproduccion) {
        this.idproduccion = idproduccion;
        this.preciodeventapormayor = preciodeventapormayor;
        this.unidaddemedida = unidaddemedida;
        this.tamanodeproduccion = tamanodeproduccion;
    }
    public Produccion(int idproduccion, Producto producto, double preciodeventapormayor, Double preciodeventapormenor, String unidaddemedida, int tamanodeproduccion, Set personas) {
       this.idproduccion = idproduccion;
       this.producto = producto;
       this.preciodeventapormayor = preciodeventapormayor;
       this.preciodeventapormenor = preciodeventapormenor;
       this.unidaddemedida = unidaddemedida;
       this.tamanodeproduccion = tamanodeproduccion;
       this.personas = personas;
    }
   
     @Id 

    
    @Column(name="idproduccion", unique=true, nullable=false)
    public int getIdproduccion() {
        return this.idproduccion;
    }
    
    public void setIdproduccion(int idproduccion) {
        this.idproduccion = idproduccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idproducto")
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    
    @Column(name="preciodeventapormayor", nullable=false, precision=17, scale=17)
    public double getPreciodeventapormayor() {
        return this.preciodeventapormayor;
    }
    
    public void setPreciodeventapormayor(double preciodeventapormayor) {
        this.preciodeventapormayor = preciodeventapormayor;
    }

    
    @Column(name="preciodeventapormenor", precision=17, scale=17)
    public Double getPreciodeventapormenor() {
        return this.preciodeventapormenor;
    }
    
    public void setPreciodeventapormenor(Double preciodeventapormenor) {
        this.preciodeventapormenor = preciodeventapormenor;
    }

    
    @Column(name="unidaddemedida", nullable=false, length=30)
    public String getUnidaddemedida() {
        return this.unidaddemedida;
    }
    
    public void setUnidaddemedida(String unidaddemedida) {
        this.unidaddemedida = unidaddemedida;
    }

    
    @Column(name="tamanodeproduccion", nullable=false)
    public int getTamanodeproduccion() {
        return this.tamanodeproduccion;
    }
    
    public void setTamanodeproduccion(int tamanodeproduccion) {
        this.tamanodeproduccion = tamanodeproduccion;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="produccions")
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


