package m.pojos;
// Generated 05-19-2016 02:23:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nombreusuario;
     private String pasword;
     private Boolean privilegio;
     private Set personas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idusuario, String nombreusuario, String pasword) {
        this.idusuario = idusuario;
        this.nombreusuario = nombreusuario;
        this.pasword = pasword;
    }
    public Usuario(int idusuario, String nombreusuario, String pasword, Boolean privilegio, Set personas) {
       this.idusuario = idusuario;
       this.nombreusuario = nombreusuario;
       this.pasword = pasword;
       this.privilegio = privilegio;
       this.personas = personas;
    }
   
     @Id 

    
    @Column(name="idusuario", unique=true, nullable=false)
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }

    
    @Column(name="nombreusuario", nullable=false, length=254)
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }

    
    @Column(name="pasword", nullable=false, length=254)
    public String getPasword() {
        return this.pasword;
    }
    
    public void setPasword(String pasword) {
        this.pasword = pasword;
    }

    
    @Column(name="privilegio")
    public Boolean getPrivilegio() {
        return this.privilegio;
    }
    
    public void setPrivilegio(Boolean privilegio) {
        this.privilegio = privilegio;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="gestiona", schema="public", joinColumns = { 
        @JoinColumn(name="idusuario", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idpersona", nullable=false, updatable=false) })
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


