package m.pojos;
// Generated 05-22-2016 04:37:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nombreusuario;
     private String pasword;
     private Boolean privilegio;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Usuario() {
    }

	
    public Usuario(int idusuario, String nombreusuario, String pasword) {
        this.idusuario = idusuario;
        this.nombreusuario = nombreusuario;
        this.pasword = pasword;
    }
    public Usuario(int idusuario, String nombreusuario, String pasword, Boolean privilegio, Set<Persona> personas) {
       this.idusuario = idusuario;
       this.nombreusuario = nombreusuario;
       this.pasword = pasword;
       this.privilegio = privilegio;
       this.personas = personas;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public String getPasword() {
        return this.pasword;
    }
    
    public void setPasword(String pasword) {
        this.pasword = pasword;
    }
    public Boolean getPrivilegio() {
        return this.privilegio;
    }
    
    public void setPrivilegio(Boolean privilegio) {
        this.privilegio = privilegio;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


