package m.pojos;
// Generated 05-22-2016 04:37:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Zona generated by hbm2java
 */
public class Zona  implements java.io.Serializable {


     private int idzona;
     private String nombrezona;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Zona() {
    }

	
    public Zona(int idzona, String nombrezona) {
        this.idzona = idzona;
        this.nombrezona = nombrezona;
    }
    public Zona(int idzona, String nombrezona, Set<Persona> personas) {
       this.idzona = idzona;
       this.nombrezona = nombrezona;
       this.personas = personas;
    }
   
    public int getIdzona() {
        return this.idzona;
    }
    
    public void setIdzona(int idzona) {
        this.idzona = idzona;
    }
    public String getNombrezona() {
        return this.nombrezona;
    }
    
    public void setNombrezona(String nombrezona) {
        this.nombrezona = nombrezona;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


