package m.pojos;
// Generated 05-19-2016 02:23:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Zona generated by hbm2java
 */
@Entity
@Table(name="zona"
    ,schema="public"
)
public class Zona  implements java.io.Serializable {


     private int idzona;
     private String nombrezona;
     private Set personas = new HashSet(0);

    public Zona() {
    }

	
    public Zona(int idzona, String nombrezona) {
        this.idzona = idzona;
        this.nombrezona = nombrezona;
    }
    public Zona(int idzona, String nombrezona, Set personas) {
       this.idzona = idzona;
       this.nombrezona = nombrezona;
       this.personas = personas;
    }
   
     @Id 

    
    @Column(name="idzona", unique=true, nullable=false)
    public int getIdzona() {
        return this.idzona;
    }
    
    public void setIdzona(int idzona) {
        this.idzona = idzona;
    }

    
    @Column(name="nombrezona", nullable=false, length=50)
    public String getNombrezona() {
        return this.nombrezona;
    }
    
    public void setNombrezona(String nombrezona) {
        this.nombrezona = nombrezona;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="zona")
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


